// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAptbxK_L5RLORw3EcicpWDAbEaz2ci5qk',
    appId: '1:554407931399:web:8a56f154604bf5de7344a2',
    messagingSenderId: '554407931399',
    projectId: 'app-bao-chay-709bd',
    authDomain: 'app-bao-chay-709bd.firebaseapp.com',
    storageBucket: 'app-bao-chay-709bd.appspot.com',
    measurementId: 'G-2F37RSX4C2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvBol2OatSDePIry-78C_tS2VSh_RZO5w',
    appId: '1:554407931399:android:25bfe01ea6734a0c7344a2',
    messagingSenderId: '554407931399',
    projectId: 'app-bao-chay-709bd',
    storageBucket: 'app-bao-chay-709bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDijx40-5MkPTvNlbkj__qNlo2PkokI-Do',
    appId: '1:554407931399:ios:77f3efd312a1fe6c7344a2',
    messagingSenderId: '554407931399',
    projectId: 'app-bao-chay-709bd',
    storageBucket: 'app-bao-chay-709bd.appspot.com',
    iosBundleId: 'com.emic.gsafesa',
  );
}
